language: swift
os: osx

matrix:
  include:
    - name: "macOS"
      script:
        - xcodebuild test -sdk macosx -project PrivacyKit.xcodeproj -scheme PrivacyKit_macOS
    - name: "iOS"
      script:
       - xcodebuild -sdk iphonesimulator -project PrivacyKit.xcodeproj -scheme PrivacyKit_iOS CODE_SIGNING_REQUIRED=NO
